# Generated by Django 3.1.4 on 2021-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
