# Generated by Django 3.1.4 on 2021-05-19 17:27

from django.db import migrations, models
import response.models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_auto_20210519_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='img',
            field=models.ImageField(upload_to=response.models.upload_to),
        ),
    ]
