# Generated by Django 3.1.4 on 2021-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_auto_20210519_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='img_count',
            field=models.IntegerField(default=0),
        ),
    ]
