# Generated by Django 3.1.4 on 2021-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_thread_img_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='watch_count',
            field=models.IntegerField(default=0),
        ),
    ]
