# Generated by Django 3.1.4 on 2021-05-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_thread_watch_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='content',
        ),
    ]
