# Generated by Django 3.1.4 on 2021-05-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_remove_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
